name: Test Dart Algorithm

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get
        working-directory: dart

      - name: Analyze
        run: dart analyze
        working-directory: dart

      - name: Test
        run: dart test
        working-directory: dart
