name: Test Scala Algorithm

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8

      - name: Test
        run: sbt -v -Dfile.encoding=UTF-8 +test
        working-directory: scala
