name: Test F# Algorithm

on:
  push:
    branches:
      - master
    paths:
      - 'fsharp/**'
  pull_request:
    branches:
      - master
    paths:
      - 'fsharp/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.201

      - name: Test
        run: dotnet test
        working-directory: fsharp
