name: Test Rust Algorithm

on:
  push:
    branches:
      - master
    paths:
      - 'rust/**'
  pull_request:
    branches:
      - master
    paths:
      - 'rust/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: marcopolo/cargo@master
        with:
          command: test
          working-directory: rust
