name: Test Go Algorithm

on:
  push:
    branches:
      - master
    paths:
      - 'go/**'
  pull_request:
    branches:
      - master
    paths:
      - 'go/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Test
        run: go test ./... -v
        working-directory: go
