name: Test F# Algorithm

on:
  push:
    branches:
      - main
    paths:
      - 'fsharp/**'
      - '.github/workflows/test-fsharp.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Test
        run: dotnet test
        working-directory: fsharp
