name: Test Rust Algorithm

on:
  push:
    branches:
      - main
    paths:
      - 'rust/**'
      - '.github/workflows/test-rust.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: cargo test
        working-directory: rust
