name: Test Haskell Algorithm

on:
  push:
    branches:
      - main
    paths:
      - 'haskell/**'
      - '.github/workflows/test-haskell.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: haskell/actions/setup@v2

      - name: Update Dependencies
        run: cabal v2-update --enable-tests
        working-directory: haskell

      - name: Install Dependencies
        run: cabal v2-install
        working-directory: haskell

      - name: Build
        run: cabal v2-build --enable-tests
        working-directory: haskell

      - name: Test
        run: cabal v2-test --enable-tests
        working-directory: haskell
